services:
  themes:
    extends:
      file: ../../docker-compose.yml
      service: themes

  redis:
    extends:
      file: ../../docker-compose.yml
      service: redis

  core:
    extends:
      file: ../../docker-compose.yml
      service: core

  chat:
    extends:
      file: ../../docker-compose.yml
      service: chat

  echo:
    build:
      context: ./echo
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - core
